name: Release Automation

on:
  workflow_dispatch:  # Enables manual triggering
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install  # Using npm instead of yarn

      - name: Build package
        run: npm run build  # Assuming you have a build script defined in package.json

      - name: Run release-it
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx release-it --verbose  # Run release-it for versioning and publishing

      - name: Notify Success
        if: success()
        run: echo "Release successful!"

      - name: Notify Failure
        if: failure()
        run: |
          echo "Release failed!"
          cat /home/runner/.npm/_logs/*.log  # Print np
