name: Release & Publish to NPM
# on: workflow_dispatch
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      # Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Checkout source code
      - uses: actions/checkout@v3

      # Clear NPM cache
      - run: npm cache clean --force

      # Install dependencies
      - run: npm ci --prefer-offline --retry 3

      # Initialize NPM config with token
      - run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      # Set Git user
      - run: |
          git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
          git config --global user.name ${{ secrets.GIT_USER_NAME }}

      # Log git status
      - run: git status

      # Run release-it
      - run: |
          npx release-it
          echo "Release process completed successfully."
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}

      # If the release step fails, print and upload the NPM error log
      - if: failure()
        run: |
          echo "Release process failed. Check the NPM error log for details."
          cat /home/runner/.npm/_logs/*-debug-0.log

      - if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: npm-error-log
          path: /home/runner/.npm/_logs/*-debug-0.log
