name: Release & Publish to NPM
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install the dependencies
      run: npm ci

    - name: Initialise the NPM config
      run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Initialize Git user
      run: |
        git config --global user.email "biplav413@gmail.com"
        git config --global user.name "Biplav-05"

    - name: Log git status
      run: git status

    - name: Run release
      run: npm run release --ci
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    # Print NPM log file in case of failure
    - name: Print NPM error log
      if: failure()
      run: cat /home/runner/.npm/_logs/*-debug-0.log

    # Upload NPM log file as an artifact in case of failure
    - name: Upload NPM error log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: npm-error-log
        path: /home/runner/.npm/_logs/*-debug-0.log
