name: Release & Publish to NPM
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'v18.19.1'

    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Clear NPM cache
      run: npm cache clean --force

    - name: Install the dependencies with retries
      run: npm ci --prefer-offline --retry 3

    - name: Initialise the NPM config
      run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Initialize Git user
      run: |
        git config --global user.email "biplav413@gmail.com"
        git config --global user.name "Biplav-05"

    - name: Log git status
      run: git status

    - name: Run release
      run: npm run release --ci
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

    # If the release step fails, print and upload the NPM error log
    - name: Print NPM error log
      if: failure()
      run: cat /home/runner/.npm/_logs/*-debug-0.log

    - name: Upload NPM error log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: npm-error-log
        path: /home/runner/.npm/_logs/*-debug-0.log
