name: Release Automation

on:
  workflow_dispatch:  # Enables manual triggering of the workflow

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Set Git user identity
        run: |
          git config --global user.email "biplav413@gmail.com"
          git config --global user.name "Biplav-05"

      - name: Enable GitHub Actions Debugging
        run: |
          echo "GITHUB_ACTIONS: ${{ env.GITHUB_ACTIONS }}"
          echo "Enable debug logs"
          echo "::set-env name=ACTIONS_STEP_DEBUG::true"
          echo "::set-env name=ACTIONS_RUNNER_DEBUG::true"
      
      - name: Install dependencies
        run: npm ci

      - name: Run release-it
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          set -e
          npx release-it --verbose
