name: Release Automation

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set Git user identity
        run: |
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Configure npm for publishing
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Debug Information
        run: |
          echo "Current version in package.json:"
          cat package.json | jq .version
          echo "Last commit message:"
          git log -1 --pretty=%B

      - name: Run release-it
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx release-it --verbose

      - name: Notify Success
        if: success()
        run: echo "Release successful!"

      - name: Notify Failure
        if: failure()
        run: |
          echo "Release failed!"
          cat /home/runner/.npm/_logs/*.log
